# Based on ripgrep's release action:
# https://github.com/BurntSushi/ripgrep/blob/master/.github/workflows/release.yml

name: Build Release Binaries
on:
  release:
    types: [published]

jobs:
  build-release:
    name: release ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        target:
        - x86_64-unknown-linux-musl
        - aarch64-unknown-linux-musl
        - armv7-unknown-linux-musleabi
        - riscv64gc-unknown-linux-musl
        - x86_64-apple-darwin
        - aarch64-apple-darwin
        - x86_64-pc-windows-msvc
        - aarch64-pc-windows-msvc
        include:
        # default configuration
        - os: ubuntu-latest
          musl: false

        # musl targets
        - target: x86_64-unknown-linux-musl
          musl: x86_64-linux-musl
        - target: aarch64-unknown-linux-musl
          musl: aarch64-linux-musl
        - target: armv7-unknown-linux-musleabi
          musl: arm-linux-musleabi
        - target: riscv64gc-unknown-linux-musl
          musl: riscv64-linux-musl

        # darwin targets
        - target: x86_64-apple-darwin
          os: macos-latest
        - target: aarch64-apple-darwin
          os: macos-latest

        # msvc targets
        - target: x86_64-pc-windows-msvc
          os: windows-latest
        - target: aarch64-pc-windows-msvc
          os: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.82.0
      with:
        target: ${{ matrix.target }}

    - name: Download Musl Toolchains
      if: ${{ matrix.musl }}
      run: |
        TOOLCHAIN_DIR=$(mktemp -d)
        curl --retry 3 -fsSL https://musl.cc/${{ matrix.musl }}-cross.tgz | tar xzf - -C $TOOLCHAIN_DIR
        echo $TOOLCHAIN_DIR/${{ matrix.musl }}-cross/bin >> $GITHUB_PATH

    - name: Build Typst CLI (w/o musl)
      if: ${{ !matrix.musl }}
      run: cargo build -p typst-cli --release --target ${{ matrix.target }} --features self-update

    - name: Build Typst CLI (w/  musl)
      if: ${{ matrix.musl }}
      run: cargo build -p typst-cli --release --target ${{ matrix.target }} --features self-update,vendor-openssl

    - name: Create Artifact Directory
      shell: bash
      run: |
        directory=typst-${{ matrix.target }}
        mkdir $directory
        cp README.md LICENSE NOTICE $directory
        if [ -f target/${{ matrix.target }}/release/typst.exe ]; then
          cp target/${{ matrix.target }}/release/typst.exe $directory
          7z a -r $directory.zip $directory
        else
          cp target/${{ matrix.target }}/release/typst $directory
          tar cJf $directory.tar.xz $directory
        fi

    - uses: ncipollo/release-action@v1.14.0
      with:
        artifacts: "typst-${{ matrix.target }}.*"
        allowUpdates: true
        omitNameDuringUpdate: true
        omitBodyDuringUpdate: true
